### ISSUE TITLE
使用插件时，疯狂报错，无法使用插件内容

### ISSUE THREAD

**Issue by Magic-King** [Acmesec/CTFCrackTools#22]
QAQ今天想尝试一波，然后放进自己的工具箱里，但是在尝试插件时连续报错

报错内容如下：
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value                                                  at org.python.core.PyString.<init>(PyString.java:64)                                                                    at org.python.core.PyString.<init>(PyString.java:70)                                                                    at org.python.core.Py.newString(Py.java:643)                                                                            at org.python.core.Py.fromIOException(Py.java:237)                                                                      at org.python.core.Py.IOError(Py.java:212)                                                                              at org.python.core.__builtin__.execfile_flags(__builtin__.java:522)                                                     at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)                                               at Core$buildPluginMenuItem$1.actionPerformed(Core.kt:847)                                                              at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)                                                       at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)                                                   at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)                                                   at javax.swing.DefaultButtonModel.setPressed(Unknown Source)                                                            at javax.swing.AbstractButton.doClick(Unknown Source)                                                                   at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)                                                       at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)                                         at java.awt.Component.processMouseEvent(Unknown Source)                                                                 at javax.swing.JComponent.processMouseEvent(Unknown Source)                                                             at java.awt.Component.processEvent(Unknown Source)                                                                      at java.awt.Container.processEvent(Unknown Source)                                                                      at java.awt.Component.dispatchEventImpl(Unknown Source)                                                                 at java.awt.Container.dispatchEventImpl(Unknown Source)                                                                 at java.awt.Component.dispatchEvent(Unknown Source)                                                                     at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)                                                    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)                                                     at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)                                                         at java.awt.Container.dispatchEventImpl(Unknown Source)                                                                 at java.awt.Window.dispatchEventImpl(Unknown Source)                                                                    at java.awt.Component.dispatchEvent(Unknown Source)                                                                     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)                                                                at java.awt.EventQueue.access$500(Unknown Source)                                                                       at java.awt.EventQueue$3.run(Unknown Source)                                                                            at java.awt.EventQueue$3.run(Unknown Source)                                                                            at java.security.AccessController.doPrivileged(Native Method)                                                           at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                        at java.awt.EventQueue$4.run(Unknown Source)                                                                            at java.awt.EventQueue$4.run(Unknown Source)                                                                            at java.security.AccessController.doPrivileged(Native Method)                                                           at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                        at java.awt.EventQueue.dispatchEvent(Unknown Source)                                                                    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)                                                  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)                                                     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)                                                  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                              at java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                              at java.awt.EventDispatchThread.run(Unknown Source)                                                             kotlin.TypeCastException: null cannot be cast to non-null type org.python.core.PyFunction                                       at Core$buildPluginMenuItem$1.actionPerformed(Core.kt:890)                                                              at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)                                                       at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)                                                   at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)                                                   at javax.swing.DefaultButtonModel.setPressed(Unknown Source)                                                            at javax.swing.AbstractButton.doClick(Unknown Source)                                                                   at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)                                                       at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)                                         at java.awt.Component.processMouseEvent(Unknown Source)                                                                 at javax.swing.JComponent.processMouseEvent(Unknown Source)                                                             at java.awt.Component.processEvent(Unknown Source)                                                                      at java.awt.Container.processEvent(Unknown Source)                                                                      at java.awt.Component.dispatchEventImpl(Unknown Source)                                                                 at java.awt.Container.dispatchEventImpl(Unknown Source)                                                                 at java.awt.Component.dispatchEvent(Unknown Source)                                                                     at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)                                                    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)                                                     at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)                                                         at java.awt.Container.dispatchEventImpl(Unknown Source)                                                                 at java.awt.Window.dispatchEventImpl(Unknown Source)                                                                    at java.awt.Component.dispatchEvent(Unknown Source)                                                                     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)                                                                at java.awt.EventQueue.access$500(Unknown Source)                                                                       at java.awt.EventQueue$3.run(Unknown Source)                                                                            at java.awt.EventQueue$3.run(Unknown Source)                                                                            at java.security.AccessController.doPrivileged(Native Method)                                                           at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                        at java.awt.EventQueue$4.run(Unknown Source)                                                                            at java.awt.EventQueue$4.run(Unknown Source)                                                                            at java.security.AccessController.doPrivileged(Native Method)                                                           at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                        at java.awt.EventQueue.dispatchEvent(Unknown Source)                                                                    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)                                                  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)                                                     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)                                                  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                              at java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                              at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by 0Chencc** [comment]
贴一下import的库

**Comment by Magic-King** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
{
        title: test,
        type: crypto,
        author: YellowTail,
        detail: test,
		Dialog: null
}
'''

def test(word):
	print("test!")
	return word+"\nsuccess test!"
	
def main(wordin)
	return test(wordin)



没有import库，在自己尝试使用test的时候报错了

**Comment by 0Chencc** [comment]
hello 很抱歉到现在才能回复你的这个issue
这个错误我已经找到了，原因是我限制死了对type向的判断，即当存在空格 逗号这样的符号的时候，没办法匹配识别。
以及在dialog的时候，我将你填的null值识别为了窗口，所以会弹出输入null的窗口，导致实际上调用的main函数是会传入一个null的值...
![image](https://user-images.githubusercontent.com/19362246/79231184-440c3180-7e98-11ea-8112-0e01bb509573.png)
我将在新版本修复

**Comment by 0Chencc** [comment]
hello 很抱歉时隔这么久才给你回复
你这段代码我跑了一次，存在这么几个问题
注释里面的各个类别建议别加上逗号，
然后就是你的def main(wordin)没有加上：导致无法调用
还需要注意的是 如果加上\n换行的话，框架只能读取最后一行的返回值。
你可以将返回的值储存到一个string值里面，这样就可以完整显示了

**Comment by 0Chencc** [comment]
```Python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
{
title:test
type:crypto
author:YellowTail
detail:test
Dialog:
}
'''

def test(word):
    return word+"\nsuccess test!"

def main(wordin):
    return test(wordin)
```
如果不需要dialog的话不需要写null，而是空出来，这是我修改之后的代码，可以尝试下，可以运行。

**Comment by Magic-King** [comment]
首先对我上次的一些python的基本错误道歉，上次应该是由于自身粗心而导致的语法问题
但是这是还是运行错误了，这是我软件版本问题吗（假如你从上次到现在还没更新的话）？
我用了你的代码贴上去，然后根据你说的把字符串存储到一个str里了，但是仍是运行报错
你给的原来的代码也是报一样的错误
插件代码如下

`#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
{
title:test
type:crypto
author:YellowTail
detail:test
Dialog:
}
'''

def test(word):
	s = word+"\nsuccess test!"
    return s

def main(wordin):
    return test(wordin)`

以下是cmd报错的代码:

`D:\0\Tool\Misc\CTFCrackTool\CTFCrackTools>java -jar CTFCrackToolsKt-3.2.3.jar
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:64)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.Py.newString(Py.java:643)
        at org.python.core.Py.fromIOException(Py.java:237)
        at org.python.core.Py.IOError(Py.java:212)
        at org.python.core.__builtin__.execfile_flags(__builtin__.java:522)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
        at Core$buildPluginMenuItem$1.actionPerformed(Core.kt:847)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
kotlin.TypeCastException: null cannot be cast to non-null type org.python.core.PyFunction
        at Core$buildPluginMenuItem$1.actionPerformed(Core.kt:890)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

`

**Comment by 0Chencc** [comment]
把原来储存在配置文件里的插件删了，重新添加一下。就可以解决了

**Comment by Magic-King** [comment]
十分感谢
