### ISSUE TITLE
python脚本中带import re会报错

### ISSUE THREAD

**Issue by linnoah** [Acmesec/CTFCrackTools#23]
运行环境 Win 10，JDK 1.8。
```
D:\tools\CTFCrackTools>java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
运行的插件脚本：
```
import re

def main(lstr):
    return lstr + 'done'
```
若无import语句，脚本正常执行。但如果有import语句，则抛出以下异常：

D:\PentestBox\bin\Ctf\decode\CTFCrackTools 1>java -jar CTFCrackToolsKt-3.2.4.jar
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:64)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.Py.newString(Py.java:643)
        at org.python.core.io.FileIO.<init>(FileIO.java:70)
        at org.python.core.PyFile.<init>(PyFile.java:161)
        at org.python.core.PyTraceback.getLine(PyTraceback.java:65)
        at org.python.core.PyTraceback.tracebackInfo(PyTraceback.java:38)
        at org.python.core.PyTraceback.dumpStack(PyTraceback.java:109)
        at org.python.core.PyTraceback.dumpStack(PyTraceback.java:120)
        at org.python.core.Py.displayException(Py.java:1182)
        at org.python.core.PySystemState.excepthook(PySystemState.java:1442)
        at org.python.core.PySystemStateFunctions.__call__(PySystemState.java:1816)
        at org.python.core.Py.printException(Py.java:1155)
        at org.python.core.Py.printException(Py.java:1114)
        at org.python.core.PyException.printStackTrace(PyException.java:66)
        at Core$buildPluginMenuItem$1.actionPerformed(Core.kt:864)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
        at java.awt.Container.dispatchEventImpl(Container.java:2281)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by 0Chencc** [comment]
对，这个问题是Jython的问题，我近期会研究一下怎么解决这个问题
