### ISSUE TITLE
文档说支持的requests库导入也报错

### ISSUE THREAD

**Issue by euzenlee** [Acmesec/CTFCrackTools#31]
没有第三方库支持，python发挥不了作用啊。

Traceback (most recent call last):
  File "D:\CTFTools\Crypto\CTFcrackTools\plugins\test.py", line 11, in <module>
    import requests
  File "D:\CTFTools\Crypto\CTFcrackTools\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "D:\CTFTools\Crypto\CTFcrackTools\Lib\site-packages\urllib3\__init__.py", line 5, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
java.lang.NullPointerException: null cannot be cast to non-null type org.python.core.PyFunction

**Comment by euzenlee** [comment]
Core.kt 第852行
            props["python.home"]=System.getProperty("user.dir")+"/Lib"
改为：
            props["python.home"]=System.getProperty("user.dir")
就可以了。

**Comment by 0Chencc** [comment]
幸苦了。
